{{- $secretName := include "argocd-repository-generator.fullname" . -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- $token := "" -}}
{{- if $existingSecret -}}
{{-   $token = (index $existingSecret.data "token") -}}
{{- else -}}
{{-   $token = (randAlphaNum 32 | b64enc) -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/part-of: argocd
    {{- include "argocd-repository-generator.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ $token | quote }}

