name: release oci chart

on:
  push:
    branches:
      - 'main'
    paths:
      - 'chart/Chart.yaml'

jobs:
  release-chart:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push chart
        run: |
          CHART_VERSION=$(grep '^version:' chart/Chart.yaml | awk '{print $2}')
          helm package chart
          helm push argocd-repository-generator-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
